### ISSUE TITLE
GPURayTracingAccelerationContainerFlag is not defined

### ISSUE THREAD

**Issue by callmegaga** [maierfelix/WebGPU-Path-Tracer#3]
I run this project on win10, and I installed the Windows 452.28 vulkan beta driver, I got this error.

> (node:19768) UnhandledPromiseRejectionWarning: ReferenceError: GPURayTracingAccelerationContainerFlag is not defined
    at GeometryBuffer.init (file:///E:/PHPStormProjects/WebGPU-Path-Tracer/buffers/GeometryBuffer.mjs:99:14)
    at new GeometryBuffer (file:///E:/PHPStormProjects/WebGPU-Path-Tracer/buffers/GeometryBuffer.mjs:12:10)
    at RayTracingPass.init (file:///E:/PHPStormProjects/WebGPU-Path-Tracer/passes/RayTracingPass.mjs:63:24)
    at new RayTracingPass (file:///E:/PHPStormProjects/WebGPU-Path-Tracer/passes/RayTracingPass.mjs:16:10)
    at main (file:///E:/PHPStormProjects/WebGPU-Path-Tracer/index.mjs:211:16)
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by mcclure** [comment]
I ran this project on Win10 with a 3070ti GPU and node/npm installed from the Windows Node LTS [14.17.3] installer on the nodejs.org website..
I did not install the vulkan driver, instead I altered index.mjs so that GPU.requestAdapter had `preferredBackend: "D3D12"`.
I got a blank window for about 3 seconds, then it closed and the console printed this same error:
```
> @ start C:\Users\Andi\work\chrome\WebGPU-Path-Tracer
> node index.mjs

(node:21100) UnhandledPromiseRejectionWarning: ReferenceError: GPURayTracingAccelerationContainerFlag is not defined
    at GeometryBuffer.init (file:///C:/Users/Andi/work/chrome/WebGPU-Path-Tracer/buffers/GeometryBuffer.mjs:99:14)
    at new GeometryBuffer (file:///C:/Users/Andi/work/chrome/WebGPU-Path-Tracer/buffers/GeometryBuffer.mjs:12:10)
    at RayTracingPass.init (file:///C:/Users/Andi/work/chrome/WebGPU-Path-Tracer/passes/RayTracingPass.mjs:63:24)
    at new RayTracingPass (file:///C:/Users/Andi/work/chrome/WebGPU-Path-Tracer/passes/RayTracingPass.mjs:16:10)
    at main (file:///C:/Users/Andi/work/chrome/WebGPU-Path-Tracer/index.mjs:211:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
